<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Puzzle game</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1>Correctly label the boxes</h1>

            <p>You know that each is labeled incorrectly. You may ask me to pick one fruit from one box which you
                choose.</p>
        </div>
    </div>

    <form>
        <div class="row">
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-danger" role="alert">Labeling is  incorrect</div>
                    <button type="submit" value="1" class="btn btn-block btn-primary" name="tryAgain">Try again</button>
                </div>
            </div>
        </div>
    </form>
</div>

</body>
</html>