<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Puzzle game</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1>Correctly label the boxes</h1>

            <p>You know that each is labeled incorrectly. You may ask me to pick one fruit from one box which you
                choose.</p>
        </div>
    </div>

    <form>
        <div class="row">
            <?php foreach ($boxes as $key => $box) : ?>

                <div class="col-xs-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">Box <?= $key; ?></div>
                        <div class="panel-body">
                            <?php if ($key == $selectedBox) : ?>
                                <p class="text-center"> <?= $box['label']; ?> / <?= $box['content']; ?></p>
                            <?php else : ?>
                                <p class="text-center"> <?= $box['label']; ?></p>
                            <?php endif ?>

                            <label for="newBoxLabel_<?= $key ?>">Select new label</label>
                            <select id="newBoxLabel_<?= $key ?>" name="newBoxLabels[<?= $key ?>]">
                                <?php foreach ($boxContent as $content): ?>
                                    <option value="<?= $content ?>"><?= $content ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div
            <?php endforeach; ?>
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-primary btn-block">
                        Set new labels
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

</body>
</html>