<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Puzzle game</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css">
</head>
<body >
<div class="container" style="color: <?= $color;?>">



    <form>
        <div class="row">
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-primary btn-block">                        Click
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

</body>
</html>